### ISSUE TITLE
convert checkboxes to radio buttons

### ISSUE THREAD

**Issue by nusenu** [erans/torcontactinfogenerator#4]
checkboxes only allow binary answers but the operator has 3 options
example:
Does your resolver perform DNSSEC validation?
[ ] yes [ ] no [x] don't want to say/ don't know

**Comment by erans** [comment]
Fixed

**Comment by nusenu** [comment]
I still see lots of checkboxes?

(The DNSSEC validation item was just meant as an example for all the checkboxes)

**Comment by erans** [comment]
Are you accessing https://torcontactinfogenerator.netlify.com or running locally?

It might be a browser cache issue. See the attached screenshot of https://torcontactinfogenerator.netlify.com.

![screenshot_2018-07-30 tor contactinfo generator](https://user-images.githubusercontent.com/10771/43422222-e854153c-93fd-11e8-8ffe-fcceb1b01a37.png)

**Comment by nusenu** [comment]
Eran Sandler:
> Are you accessing https://torcontactinfogenerator.netlify.com or running locally?

I'm accessing https://torcontactinfogenerator.netlify.com but can rule out caching.

> It might be a browser cache issue. See the attached screenshot of https://torcontactinfogenerator.netlify.com.

your screenshot shows a checkbox for the QNAME field (the 'dnssec' field was meant as an **example**).


To avoid further confusion I'll list them specifically (instead of saying 'all the checkboxes'):

- offlinemasterkey
- sandboxing
- aesni
- autoupdate
- dnsqname
- dnslocalrootzone


Scheduler is currently a checkbox but will become a drop down menu (#6)


Referencing the issue in commit messages also make misunderstandings
more spotable.

(878ed2bd99272971045d83b0275e33107a3300bf only touches the 'dnssec' field)
